TestMSSQL/Models/CpuMetric.cs
using Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestMSSQL.Models
{
    public class CpuMetric :BaseEntity
    {
        

        public int Value { get; set; }

        public DateTime Time { get; set; }

    }
}

TestMSSQL/Controllers/CpuMetricController.cs
using Core;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TestMSSQL.Models;

namespace TestMSSQL.Controllers
{
    public class CpuMetricController : Controller
    {
        private readonly ILogger<CpuMetricController> _logger;
        private readonly IDbRepository<CpuMetric> _cpuMetricyRepo;


        private ApplicationContext db;
        public CpuMetricController(ApplicationContext context, ILogger<CpuMetricController> logger, IDbRepository<CpuMetric> cpuMetricyRepo)
        {
            db = context;
            _logger = logger;
            _cpuMetricyRepo = cpuMetricyRepo;
        }


        public async Task<IActionResult> Index()
        {
            return View(await db.CpuMetrics.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CpuMetric сpuMetric)
        {
            db.CpuMetrics.Add(сpuMetric);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id != null)
        //    {
        //        User user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
        //        if (user != null)
        //            return View(user);
        //    }
        //    return NotFound();
        //}



        //public async Task<IActionResult> Edit(int? id)
        //{
        //    if (id != null)
        //    {
        //        User user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
        //        if (user != null)
        //            return View(user);
        //    }
        //    return NotFound();
        //}
        //[HttpPost]
        //public async Task<IActionResult> Edit(User user)
        //{
        //    db.Users.Update(user);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        //[HttpGet]
        //[ActionName("Delete")]
        //public async Task<IActionResult> ConfirmDelete(int? id)
        //{
        //    if (id != null)
        //    {
        //        User user = await db.Users.FirstOrDefaultAsync(p => p.Id == id);
        //        if (user != null)
        //            return View(user);
        //    }
        //    return NotFound();
        //}

        

        //[HttpPost]
        //public async Task<IActionResult> Delete(int? id)
        //{
        //    if (id != null)
        //    {
        //        User user = new User { Id = id.Value };
        //        db.Entry(user).State = EntityState.Deleted;
        //        await db.SaveChangesAsync();
        //        return RedirectToAction("Index");
        //    }
        //    return NotFound();
        //}

        //public IActionResult Privacy()
        //{
        //    return View();
        //}

        //[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        //public IActionResult Error()
        //{
        //    return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        //}
    }
}

TestMSSQL/Views/CpuMetric/Create.cshtml
@model TestMSSQL.Models.CpuMetric
@{
    ViewBag.Title = "Добавление пользователя";
}
<form asp-action="create" asp-controller="CpuMetric">
    <div class="form-group">
        <label asp-for="Id" class="control-label">Id</label>
        <input type="text" asp-for="Time" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Value" class="control-label">Value</label>
        <input type="number" asp-for="Value" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Отправить" class="btn btn-default" />
    </div>
</form>

TestMSSQL/Views/CpuMetric/Index.cshtml
@model IEnumerable<TestMSSQL.Models.CpuMetric>
@{
    ViewBag.Title = "Все пользователи";
}
<a asp-action="Create">Добавить пользователя MetricManager</a>

@*<table class="table">
    <tr><td>Id</td><td>Time</td><td>Value</td></tr>
    @foreach (var item in Model)
    {
<tr>
    <td>@item.Id</td>
    <td>@item.Time</td>
    <td>@item.Value</td>
</tr>
    }
</table>*@


@*<table class="table">

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>
                <a asp-action="Details" asp-controller="Home" asp-route-id="@item.Id">Подробнее</a> |
                <a asp-action="Edit" asp-controller="Home" asp-route-id="@item.Id">Изменить</a> |
                <a asp-action="Delete" asp-controller="Home" asp-route-id="@item.Id">Удалить</a>
            </td>
        </tr>
    }
</table>*@